### ISSUE TITLE
ErrorException: Template error: Cannot call method isIgnoring on a non-object (NULL)

### ISSUE THREAD

**Issue by Nirjonadda** [LukasWieditz/EditorManager#5]
Server error log:

````
ErrorException: Template error: Cannot call method isIgnoring on a non-object (NULL) src/XF/Template/Templater.php:970 

Generated by: htitu Apr 17, 2019 at 2:46 AM 

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Cannot call met...', '/home/nadda/pub...', 970, Array)
#1 src/XF/Template/Templater.php(970): trigger_error('Cannot call met...', 512)
#2 internal_data/code_cache/templates/l1/s0/public/bb_code_tag_quote.php(9): XF\Template\Templater->method(NULL, 'isIgnoring', Array)
#3 src/XF/Template/Templater.php(1301): XF\Template\Templater->{closure}(Object(AddonFlare\PaidRegistrations\XF\Template\Templater), Array)
#4 src/addons/AddonsLab/LinkChecker/XF/Template/Templater.php(89): XF\Template\Templater->renderTemplate('bb_code_tag_quo...', Array, true)
#5 src/XF/BbCode/Renderer/Html.php(956): AddonsLab\LinkChecker\XF\Template\Templater->renderTemplate('public:bb_code_...', Array)
#6 src/XF/BbCode/Renderer/Html.php(947): XF\BbCode\Renderer\Html->getRenderedQuote('Thanks for shar...', 'Dibakor', Array, Array)
#7 [internal function]: XF\BbCode\Renderer\Html->renderTagQuote(Array, 'Dibakor, post: ...', Array, Array, Object(ThemeHouse\Giphy\XF\BbCode\Renderer\Html))
#8 src/XF/BbCode/Renderer/Html.php(295): call_user_func(Array, Array, 'Dibakor, post: ...', Array, Array, Object(ThemeHouse\Giphy\XF\BbCode\Renderer\Html))
#9 src/addons/KL/EditorManager/XF/BbCode/Renderer/EditorManager.php(110): XF\BbCode\Renderer\Html->renderTag(Array, Array)
#10 src/XF/BbCode/Traverser.php(61): KL\EditorManager\XF\BbCode\Renderer\Html->renderTag(Array, Array)
#11 src/XF/BbCode/Traverser.php(37): XF\BbCode\Traverser->renderSubTree(Array, Array)
#12 src/XF/BbCode/Traverser.php(20): XF\BbCode\Traverser->renderAst(Array, Object(SV\AdvancedBbCodesPack\XF\BbCode\RuleSet), Array)
#13 src/XF/SubContainer/BbCode.php(219): XF\BbCode\Traverser->render('[QUOTE="Dibakor...', Object(SV\AdvancedBbCodesPack\XF\BbCode\Parser), Object(SV\AdvancedBbCodesPack\XF\BbCode\RuleSet), Array)
#14 src/addons/KL/EditorManager/XF/Pub/Controller/Post.php(29): XF\SubContainer\BbCode->render('[QUOTE="Dibakor...', 'html', 'post', Object(SV\ChangePostDate\XF\Entity\Post))
#15 src/XF/Mvc/Dispatcher.php(321): KL\EditorManager\XF\Pub\Controller\Post->actionReact(Object(XF\Mvc\ParameterBag))
#16 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('XF:Post', 'React', Object(XF\Mvc\RouteMatch), Object(TickTackk\ContentCopyProtection\XF\Pub\Controller\Post), NULL)
#17 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(TickTackk\ContentCopyProtection\XF\Pub\Controller\Post), NULL)
#18 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#19 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#20 src/XF.php(390): XF\App->run()
#21 index.php(20): XF::runApp('XF\\Pub\\App')
#22 {main}

Request state

array(4) {
  ["url"] => string(32) "/posts/35097/react?reaction_id=1"
  ["referrer"] => string(134) "/threads/small-sized.826/"
  ["_GET"] => array(1) {
    ["reaction_id"] => string(1) "1"
  }
  ["_POST"] => array(4) {
    ["_xfRequestUri"] => string(112) "/threads/small-sized.826/"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(8) "********"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

**Comment by LukasWieditz** [comment]
No longer able to reproduce this.
